/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasterProductsIndexRouteImport } from './routes/master/products/index'
import { Route as MasterProductCategoriesIndexRouteImport } from './routes/master/product-categories/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterProductsIndexRoute = MasterProductsIndexRouteImport.update({
  id: '/master/products/',
  path: '/master/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterProductCategoriesIndexRoute =
  MasterProductCategoriesIndexRouteImport.update({
    id: '/master/product-categories/',
    path: '/master/product-categories/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/master/product-categories/': typeof MasterProductCategoriesIndexRoute
  '/master/products/': typeof MasterProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/master/product-categories': typeof MasterProductCategoriesIndexRoute
  '/master/products': typeof MasterProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/master/product-categories/': typeof MasterProductCategoriesIndexRoute
  '/master/products/': typeof MasterProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/master/product-categories/' | '/master/products/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/master/product-categories' | '/master/products'
  id: '__root__' | '/' | '/master/product-categories/' | '/master/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MasterProductCategoriesIndexRoute: typeof MasterProductCategoriesIndexRoute
  MasterProductsIndexRoute: typeof MasterProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/products/': {
      id: '/master/products/'
      path: '/master/products'
      fullPath: '/master/products/'
      preLoaderRoute: typeof MasterProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/product-categories/': {
      id: '/master/product-categories/'
      path: '/master/product-categories'
      fullPath: '/master/product-categories/'
      preLoaderRoute: typeof MasterProductCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MasterProductCategoriesIndexRoute: MasterProductCategoriesIndexRoute,
  MasterProductsIndexRoute: MasterProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
