/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductCategoriesIndexRouteImport } from './routes/product-categories/index'
import { Route as PriceTiersIndexRouteImport } from './routes/price-tiers/index'
import { Route as PosIndexRouteImport } from './routes/pos/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as ProductsCreateRouteImport } from './routes/products/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductCategoriesIndexRoute = ProductCategoriesIndexRouteImport.update({
  id: '/product-categories/',
  path: '/product-categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceTiersIndexRoute = PriceTiersIndexRouteImport.update({
  id: '/price-tiers/',
  path: '/price-tiers/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosIndexRoute = PosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCreateRoute = ProductsCreateRouteImport.update({
  id: '/products/create',
  path: '/products/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products/create': typeof ProductsCreateRoute
  '/customers/': typeof CustomersIndexRoute
  '/pos/': typeof PosIndexRoute
  '/price-tiers/': typeof PriceTiersIndexRoute
  '/product-categories/': typeof ProductCategoriesIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products/create': typeof ProductsCreateRoute
  '/customers': typeof CustomersIndexRoute
  '/pos': typeof PosIndexRoute
  '/price-tiers': typeof PriceTiersIndexRoute
  '/product-categories': typeof ProductCategoriesIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products/create': typeof ProductsCreateRoute
  '/customers/': typeof CustomersIndexRoute
  '/pos/': typeof PosIndexRoute
  '/price-tiers/': typeof PriceTiersIndexRoute
  '/product-categories/': typeof ProductCategoriesIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/products/create'
    | '/customers/'
    | '/pos/'
    | '/price-tiers/'
    | '/product-categories/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/products/create'
    | '/customers'
    | '/pos'
    | '/price-tiers'
    | '/product-categories'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/products/create'
    | '/customers/'
    | '/pos/'
    | '/price-tiers/'
    | '/product-categories/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsCreateRoute: typeof ProductsCreateRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  PosIndexRoute: typeof PosIndexRoute
  PriceTiersIndexRoute: typeof PriceTiersIndexRoute
  ProductCategoriesIndexRoute: typeof ProductCategoriesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-categories/': {
      id: '/product-categories/'
      path: '/product-categories'
      fullPath: '/product-categories/'
      preLoaderRoute: typeof ProductCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-tiers/': {
      id: '/price-tiers/'
      path: '/price-tiers'
      fullPath: '/price-tiers/'
      preLoaderRoute: typeof PriceTiersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/': {
      id: '/pos/'
      path: '/pos'
      fullPath: '/pos/'
      preLoaderRoute: typeof PosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/create': {
      id: '/products/create'
      path: '/products/create'
      fullPath: '/products/create'
      preLoaderRoute: typeof ProductsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsCreateRoute: ProductsCreateRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  PosIndexRoute: PosIndexRoute,
  PriceTiersIndexRoute: PriceTiersIndexRoute,
  ProductCategoriesIndexRoute: ProductCategoriesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
